#cloud-config
package_update: true
package_upgrade: all
packages:
  - ufw

write_files:
  - path: /etc/default/ufw
    append: true
    content: |
      DEFAULT_FORWARD_POLICY="ACCEPT"

runcmd:
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow from 203.0.113.0/24 to any port 22 proto tcp
  - ufw allow from 203.0.113.0/24 to any port 51820 proto udp
  - ufw --force enable
