# cloud-init/edge-caddy-proxy.yaml
#cloud-config
packages:
  - curl
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https

write_files:
  - path: /etc/caddy/Caddyfile
    permissions: '0644'
    content: |
      {{ .caddyfile_content }}

runcmd:
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | apt-key add -
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  - apt update
  - apt install -y caddy
  - systemctl enable caddy
  - systemctl start caddy
