# cloud-init/edge-caddy.yaml
#cloud-config
packages:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
  - curl

#cloud-config
write_files:
  - path: /etc/caddy/Caddyfile
    content: |
      YOUR_DOMAIN {
          reverse_proxy 10.0.1.10:8080
          log {
              output file /var/log/caddy/access.log
          }
      }
runcmd:
  - systemctl enable caddy
  - systemctl start caddy

