name: Security Related Tasks

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  audit:
    name: Run NPM Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # this is from L2 task 
      - name: Run NPM Audit
        run: |
          if [ -f package-lock.json ]; then
            npm audit --audit-level=high
          else
            echo "Warning: package-lock.json not found — skipping audit"
            exit 0
          fi

      # This is really not from any task but I guess it will be consistent with checks in local branch
      # install and run TruffleHog
      - name: Install TruffleHog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | \
          sh -s -- -b /usr/local/bin

      - name: Run TruffleHog scan
        run: |
          trufflehog filesystem . 
      # here must be code to parse output and if conditions are not met reject.
      # What to check? verified obviously, how about unverified?
